// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wy1poyb9et3TtyzqiOUCwDBBkZUjcMQ',
    appId: '1:1046259329563:android:6a7675c0fec5d319c826be',
    messagingSenderId: '1046259329563',
    projectId: 'restaurant-87715',
    storageBucket: 'restaurant-87715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUs78jno9uFwjIqtgS203j9x0gakEyRM',
    appId: '1:1046259329563:ios:c79b03e680337b00c826be',
    messagingSenderId: '1046259329563',
    projectId: 'restaurant-87715',
    storageBucket: 'restaurant-87715.firebasestorage.app',
    iosBundleId: 'com.example.dalab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUs78jno9uFwjIqtgS203j9x0gakEyRM',
    appId: '1:1046259329563:ios:c79b03e680337b00c826be',
    messagingSenderId: '1046259329563',
    projectId: 'restaurant-87715',
    storageBucket: 'restaurant-87715.firebasestorage.app',
    iosBundleId: 'com.example.dalab',
  );
}
